[features]
seeds = false
skip-lint = false

[programs.localnet]
verify_ai = "3tWipTxd8Nbaqrozw3asMma3j5h1vVuwEkWJgzssPvZH"

[programs.devnet]
verify_ai = "3tWipTxd8Nbaqrozw3asMma3j5h1vVuwEkWJgzssPvZH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"  # Change this to "mainnet" for production deployment
wallet = "~/.config/solana/id.json"  # Path to your keypair
endpoint = "https://devnet.genesysgo.net/"  # Change this to your desired endpoint

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
deploy = "anchor migrate"