[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
verify_ai = "3tWipTxd8Nbaqrozw3asMma3j5h1vVuwEkWJgzssPvZH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/vandycklai/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
